# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Game of Life
tagline:          'Great minds have purpose, others have wishes.﻿——Neil Patel'
description:      'Hello,World! Here is my personal weblog about technology and life.'
url:              http://xiaotaozi.top

author:
  name:           'Xiaotaozi'
  url:            http://xiaotaozi.top

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : soohu
